name: Test

on:
  push:
    branches: ['*']

env:
  FORCE_COLOR: 1

jobs:
  test:
    name: Test
    runs-on:
      - self-hosted
      - X64
    timeout-minutes: 10
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
      - uses: oven-sh/setup-bun@v2
      - uses: 1password/install-cli-action@v1
      - uses: extractions/setup-just@v3
        with:
          just-version: 1.40.0
          github-token: ${{ github.token }}
      - name: Install Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: '0.18.19'
      - name: Test (Dagger)
        run: just dagx test
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
